baseURL = 'http://soltyscozrobilwiecej.pl/'
languageCode = 'en-us'
title = 'Sołtys - co zrobił więcej'
theme = 'autophugo'

[params]
    # Meta
    description = "Wydarzenia z kadencji `Młodego Sołtysa`"
    keywords = "sołtys, trynosy-osiedle, trynosy, pożegnanie, pożegnanie sołtysa"
    #msvalidate = ""
    #googlesiteverification = ""
    #thumb_width = 480
    thumb_quality = 100
    #full_width = 960
    full_quality = 100
    #column_count = 2
    #breadcrumb_use_title = false
    #filename_as_phototitle = false
    images_downloadable = true

